# Site settings
title: DOYNK.me
email: bruns@clichesaur.us
description: Pay ATTENTION! Your stairs are trying to kill you. Shut off fearmongering from the teevee. Your STAIRS are trying to kill you. PAY more attention to EVERY step.
twitter_username: Clichesaur_us
github_username:  FunnierBe

# Build settings
markdown: kramdown
