# Site settings
title: DOYNK.me
email: bruns@clichesaur.us
description: Pay ATTENTION! Build discipline with every step. The stairs ARE trying to kill you. Remove mindless distractions and worries. The stairs ARE trying to kill you.
twitter_username: Clichesaur_us
github_username:  FunnierBe

# Build settings
markdown: kramdown
